/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hibernate;

import java.awt.Dimension;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author bm
 */
public class SearchEmployee extends javax.swing.JFrame {

    /**
     * Creates new form SearchEmployee
     */
    public SearchEmployee() {
        initComponents();
        hideElements();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        labLeft = new javax.swing.JLabel();
        tfFirst = new javax.swing.JTextField();
        tfSecond = new javax.swing.JTextField();
        labX = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(700, 180));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Search by:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"", "Name", "Age", "Address", "Income" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        labLeft.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        tfFirst.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfSecond.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        labX.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        labX.setText("-");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)
                                .addComponent(tfFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labX, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 77, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labLeft)
                    .addComponent(tfFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labX))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String chosen = (String) ((JComboBox) evt.getSource()).getSelectedItem();
        try {
            search(chosen);
        } catch (SQLException ex) {
            Logger.getLogger(SearchEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            DefaultListModel model = new DefaultListModel();
            List<Employee> list;
            switch (option) {
                case "name":
                    list = Repo.search("name", tfFirst.getText());
                    for (Employee e : list) {
                        model.addElement(e);
                    }
                    Main.listEmp.setModel(model);
                    this.setVisible(false);
                    break;
                case "address":
                    list = Repo.search("address", tfFirst.getText());
                    for (Employee e : list) {
                        model.addElement(e);
                    }
                    Main.listEmp.setModel(model);
                    this.setVisible(false);
                    break;
                    
                case "age":
                    list = Repo.searchBetween("age", Integer.parseInt(tfFirst.getText()), Integer.parseInt(tfSecond.getText()));
                    for (Employee e : list) {
                        model.addElement(e);
                    }
                    Main.listEmp.setModel(model);
                    this.setVisible(false);
                    break;
                    
                case "income":
                    list = Repo.searchBetween("income", Integer.parseInt(tfFirst.getText()), Integer.parseInt(tfSecond.getText()));
                    for (Employee e : list) {
                        model.addElement(e);
                    }
                    Main.listEmp.setModel(model);
                    this.setVisible(false);    
                    break;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please insert number data into fields");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Please select one of the options");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    String option;

    public String search(String str) throws SQLException {
        option = null;
        switch (str) {
            case "Name":
                hideElements();
                labLeft.setVisible(true);
                labLeft.setText("Search by name:");
                tfFirst.setVisible(true);
                option = "name";
                break;
            case "Age":
                hideElements();
                labLeft.setVisible(true);
                labLeft.setText("Search by age between:");
                tfFirst.setVisible(true);
                labX.setVisible(true);
                tfSecond.setVisible(true);
                option = "age";
                break;
            case "Address":
                hideElements();
                labLeft.setVisible(true);
                labLeft.setText("Search by address:");
                tfFirst.setVisible(true);
                option = "address";
                break;
            case "Income":
                hideElements();
                labLeft.setVisible(true);
                labLeft.setText("Search by income between:");
                tfFirst.setVisible(true);
                labX.setVisible(true);
                tfSecond.setVisible(true);
                option = "income";
                break;
        }
        return option;
    }

    private void hideElements() {
        labLeft.setVisible(false);
        labX.setVisible(false);
        tfFirst.setVisible(false);
        tfSecond.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEmployee().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labLeft;
    private javax.swing.JLabel labX;
    private javax.swing.JTextField tfFirst;
    private javax.swing.JTextField tfSecond;
    // End of variables declaration//GEN-END:variables
}
